### ISSUE TITLE
Review by kuba

### ISSUE THREAD

**Issue by Stebalien** [libp2p/go-reuseport-transport#1]

**Comment by Kubuxu** [comment]
I would rename this variable: https://github.com/libp2p/go-reuseport-transport/blob/master/reuseport.go#L59 it was a bit confusing at first.

Shouldn't we use `global` in this case? https://github.com/libp2p/go-reuseport-transport/blob/master/multidialer.go#L43-L47

**Comment by Kubuxu** [comment]
We might want to catch: `EHOSTUNREACH` and redial using a different address.

**Comment by Stebalien** [comment]
> We might want to catch: EHOSTUNREACH and redial using a different address.

Different source or target? We always use the unspecified IP address for the source (this library just picks the source *port*). It's up to the transport to try multiple target addresses.

**Comment by Kubuxu** [comment]
In case of local network we use random address for Dial afaik.

**Comment by Stebalien** [comment]
We pick a random source *port* from the set of reasonable source ports but we never manually specify the source address.

Note: The swarm no longer specifies source addresses when dialing. I moved that logic into the transport because the swarm doesn't really know enough to do so intelligently.

Really, the *correct* way to implement this library would be to:

1. Ask the kernel, if I dial IP X, which source address will I use.
2. Try a random port out of all the ports we have open on that source address.

Unfortunately, the "ask the kernel" part involves using netlink. We could do this (e.g., with the [netlink](https://godoc.org/github.com/vishvananda/netlink#RouteGet) package) but that adds some complexity (and I'd like to do it later, if ever).

**Comment by Stebalien** [comment]
> Shouldn't we use global in this case? https://github.com/libp2p/go-reuseport-transport/blob/master/multidialer.go#L43-L47

No, but that needs a comment. Basically, we *always* prefer using the unspecified address over the global address because we don't actually know if the global address can dial the target. The logic is:

1. If we're dialing loopback,  choose a source-port in order of preference:
  1. A port in-use by an explicit loopback listener.
  2. A port in-use by a listener on an unspecified address (must also be listening on localhost).
  3. A port in-use by a listener on a global address. We don't have any other better options (other than picking a random port).
2. If we're dialing a global address, choose a source-port in order of preference:
  1. A port in-use by a listener on an unspecified address (the most general case).
  2. A port in-use by a listener on the global address.
3. Fail on link-local dials (go-ipfs currently forbids this and I figured we could try lifting this restriction later).

**Comment by Stebalien** [comment]
Changes: https://github.com/libp2p/go-reuseport-transport/compare/73d48b52b410ec78282a77d507c1f33f7e7c81ee...f431c22e8a8a546bdce4c5328aea039cb58ba57b

**Comment by Stebalien** [comment]
@Kubuxu when you get a chance, final review?

**Comment by Kubuxu** [comment]
SGWM
