### ISSUE TITLE
Distinguish between ipv6 and ipv4 when select source

### ISSUE THREAD

**Issue by lnykww** [libp2p/go-reuseport-transport#12]
When selecting the source address, there is no distinction between ipv4 and ipv6.It may use ipv6 address to access ipv4 address. is there a problem with this?

**Comment by Stebalien** [comment]
We do distinguish. If you look at the `Transport` type, it has two fields, a `v4` and a `v6` "network". We use one for ipv4 addresses and one for ipv6 addresses.

**Comment by lnykww** [comment]
I see that. Thanks!
