### ISSUE TITLE
Is there any plan to support quic? 

### ISSUE THREAD

**Issue by lnykww** [libp2p/go-reuseport-transport#13]

**Comment by vyzo** [comment]
QUIC is already supported! See https://github.com/libp2p/go-libp2p-quic-transport

**Comment by lnykww** [comment]
@vyzo  Maybe I didn’t make it clear.  I means that support  REUSEPORT for QUIC.  Currently this library only supports TCP REUSEPORT.

**Comment by vyzo** [comment]
oh ok, There is already some work to support reuseport for quic within the quic package.

**Comment by lnykww** [comment]
I am considering whether it is better to use the same source address selection algorithm as tcp in this library rather than in quic library?

**Comment by marten-seemann** [comment]
See https://github.com/libp2p/go-libp2p-quic-transport/issues/8.
